// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6QbYCdlbPbSwjYY1eGX9TesM8tykbThQ',
    appId: '1:193194465066:web:1754413063fdd7af1ab053',
    messagingSenderId: '193194465066',
    projectId: 'animerchapp',
    authDomain: 'animerchapp.firebaseapp.com',
    storageBucket: 'animerchapp.firebasestorage.app',
    measurementId: 'G-0LQE00ZDVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQniB9ywKJZm6aNZOLVDNQcDnkdfv2FCQ',
    appId: '1:193194465066:android:c909bb3db419ec861ab053',
    messagingSenderId: '193194465066',
    projectId: 'animerchapp',
    storageBucket: 'animerchapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdCH4U8vIl9ORZoDfJ7UnVj3u8Fpe82pY',
    appId: '1:193194465066:ios:2aa874f6b130f00a1ab053',
    messagingSenderId: '193194465066',
    projectId: 'animerchapp',
    storageBucket: 'animerchapp.firebasestorage.app',
    iosBundleId: 'com.example.animerchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6QbYCdlbPbSwjYY1eGX9TesM8tykbThQ',
    appId: '1:193194465066:web:97bad62758f6a8c51ab053',
    messagingSenderId: '193194465066',
    projectId: 'animerchapp',
    authDomain: 'animerchapp.firebaseapp.com',
    storageBucket: 'animerchapp.firebasestorage.app',
    measurementId: 'G-WEN4GTMHSC',
  );
}
